#!/usr/bin/python

""" So I guess we have to import stuff now ... """

import os
import subprocess

def speak():
	os.system('say hello')

def makefile():
	os.system('touch ~/Desktop/file ')

def all():
	speak()
	makefile()

all()